import { ReactNode } from 'react'
import Head from 'next/head'
import Nav from './Nav'
import { NEXT_PUBLIC_CHAIN_EXPLORER, NEXT_PUBLIC_CHAIN_NAME, NEXT_PUBLIC_SITE_TITLE } from 'constants/constants'

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-base-100 text-base-content">
      <Head>
<<<<<<< Updated upstream
        <title>{NEXT_PUBLIC_SITE_TITLE}</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.png"/>
=======
        <title>{process.env.NEXT_PUBLIC_SITE_TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
>>>>>>> Stashed changes
      </Head>

      <Nav />
      <main className="flex flex-col items-center justify-center w-full flex-1 p-2 md:px-20 text-center">
        {children}
      </main>
      <footer className="flex items-center justify-center w-full h-24 border-t">
        <a
<<<<<<< Updated upstream
          target="_blank" rel="noreferrer" href={NEXT_PUBLIC_CHAIN_EXPLORER || ""}
=======
>>>>>>> Stashed changes
          className="pl-1 link link-primary link-hover"
          href="/university"
        >
<<<<<<< Updated upstream
          {NEXT_PUBLIC_CHAIN_NAME} Explorer
=======
          Univeristy
>>>>>>> Stashed changes
        </a>
        <span className="pl-1"> | </span>
        <a
          className="pl-1 link link-primary link-hover"
          href="/hackaton"
        >
          Hackaton
        </a>
      </footer>
    </div>
  )
}
