/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export interface InstantiateMsg {
  purchase_price?: Coin | null;
  transfer_price?: Coin | null;
  [k: string]: unknown;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  register: {
    bio: string;
    did: string;
    username: string;
    [k: string]: unknown;
  };
};
export type QueryMsg = {
  resolve_user_info: {
    address: number[];
    [k: string]: unknown;
  };
} | {
  config: {
    [k: string]: unknown;
  };
};
export interface Config {
  purchase_price?: Coin | null;
  transfer_price?: Coin | null;
  [k: string]: unknown;
}
export interface UserInfo {
  bio: string;
  did: string;
  username: string;
  [k: string]: unknown;
}